#!/bin/bash

if [[ $# -ne 2 ]] ; then
    echo "Usage: $0 https://myserver.com /path/to/key"
    exit 1
fi

URL=$1
KEY=$2

/usr/bin/piky-update-get $URL /tmp/blob \
    && /usr/bin/piky-update-extract $KEY /tmp/blob \
    && /tmp/payload/run.sh
